### ISSUE TITLE
[social affiliations]

### ISSUE THREAD

**Issue by vsoch** [openbases/docs#5]
a discussion for down the road (that I'll put here so I don't forget) is how we want to engage with the community. It might be via existing avenues (e.g., personal and associated twitter or similar) or via a themed account just for it. For now, I'm just putting these as place holders:

```
extra:
  social:
    - type: 'github'
      link: 'https://github.com/openbases'
    - type: 'docker'
      link: 'http://hub.docker.com/r/openbases'
    - type: 'twitter'
      link: 'https://twitter.com/vsoch'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/vsochat'
```
Not sure if Docker is an allowed type, but if not, I'll open an issue / PR so it renders nicely for the theme.
